title: PROtect 
description: A password manager to save, retrieve, update personal passwords and usernames related to websites and applications. 
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
